@startuml
interface NFIKernelModule
interface NFMapEx
class NFKernelModule{

	NFISceneModule* m_pSceneModule;
    NFILogModule* m_pLogModule;
    NFIClassModule* m_pClassModule;
    NFIElementModule* m_pElementModule;
	NFIScheduleModule* m_pScheduleModule;
	NFIEventModule* m_pEventModule;
    NFICellModule* m_pCellModule;
    NFIThreadPoolModule* m_pThreadPoolModule;
}
NFIKernelModule <|-- NFKernelModule
NFMapEx <|-- NFKernelModule
@enduml